import { NextRequest, NextResponse } from "next/server"
import { getScan, getScanFindings } from "@/lib/firestore-service"

export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const scan = await getScan(id)
  if (!scan) return NextResponse.json({ error: "Scan not found" }, { status: 404 })

  const url = new URL(request.url)
  const format = url.searchParams.get("format") || "json"

  if (format === "json") {
    return NextResponse.json(scan)
  }

  const findings = await getScanFindings(id)

  if (format === "csv") {
    const headers = ["module", "id", "category", "severity", "title", "description", "passed"]
    const rows = findings.map((f: Record<string, unknown>) =>
      [f.module, f.id, f.category, f.severity, `"${(f.title as string || "").replace(/"/g, '""')}"`, `"${(f.description as string || "").replace(/"/g, '""')}"`, f.passed].join(",")
    )
    const csv = [headers.join(","), ...rows].join("\n")
    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv",
        "Content-Disposition": `attachment; filename="scan-${id}.csv"`,
      },
    })
  }

  if (format === "pdf") {
    const modules = ["security", "seo", "aeo", "performance", "indexing", "aiReadiness", "domain", "accessibility"] as const
    const moduleScores = modules.map((m) => {
      const mod = (scan as unknown as Record<string, unknown>)[m] as { score?: number; grade?: string } | undefined
      return { module: m, score: mod?.score ?? 0, grade: mod?.grade ?? "N/A" }
    })
    const totalFindings = findings.length
    const passedFindings = findings.filter((f: Record<string, unknown>) => f.passed).length

    const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Scan Report - ${scan.url}</title>
<style>
  body { font-family: Inter, system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #111; }
  h1 { font-size: 24px; font-weight: 600; margin-bottom: 4px; }
  .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
  .overall { font-size: 48px; font-weight: 700; margin: 24px 0; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #e5e5e5; font-size: 14px; }
  th { font-weight: 600; color: #555; text-transform: uppercase; font-size: 11px; letter-spacing: 0.5px; }
  .pass { color: #16a34a; } .fail { color: #ea580c; }
  .summary { display: flex; gap: 24px; margin: 16px 0; }
  .summary-item { flex: 1; background: #f9f9f9; border-radius: 12px; padding: 16px; }
  .summary-item .label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
  .summary-item .value { font-size: 28px; font-weight: 700; margin-top: 4px; }
</style></head>
<body>
  <h1>Scan Report</h1>
  <p class="subtitle">${scan.url} &bull; ${new Date(scan.createdAt).toLocaleDateString()} &bull; ${scan.durationMs}ms</p>
  <div class="overall">${scan.overallScore}/100 <span style="font-size:18px;color:#666;">(${scan.overallGrade})</span></div>
  <div class="summary">
    <div class="summary-item"><div class="label">Findings</div><div class="value">${totalFindings}</div></div>
    <div class="summary-item"><div class="label">Passed</div><div class="value">${passedFindings}</div></div>
    <div class="summary-item"><div class="label">Failed</div><div class="value">${totalFindings - passedFindings}</div></div>
  </div>
  <table>
    <tr><th>Module</th><th>Score</th><th>Grade</th></tr>
    ${moduleScores.map((m) => `<tr><td style="text-transform:capitalize">${m.module}</td><td>${m.score}</td><td>${m.grade}</td></tr>`).join("\n    ")}
  </table>
  <table>
    <tr><th>Finding</th><th>Severity</th><th>Status</th></tr>
    ${findings.slice(0, 100).map((f: Record<string, unknown>) =>
      `<tr><td>${f.title}</td><td>${f.severity}</td><td class="${f.passed ? "pass" : "fail"}">${f.passed ? "PASS" : "FAIL"}</td></tr>`
    ).join("\n    ")}
  </table>
  <p style="color:#999;font-size:12px;margin-top:40px;">Generated by WebCore &bull; ${new Date().toISOString()}</p>
</body></html>`

    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `inline; filename="scan-${id}.html"`,
      },
    })
  }

  return NextResponse.json(scan)
}
